pub mod coin_row;
pub mod coin_change_making;
pub mod coin_collecting;
pub mod minimum_sum_descent;
pub mod minimum_sum_descent2;
pub mod knapsack;
pub mod coin_change_making_v2;
pub mod text_parser;
pub mod word_breaker;
